spring:

  application:
    name: hotel-reservation

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hotel_reservation
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    #this will create table if it doesn't exist and update if exist
    #and will replace it with validate soon, read about it and make sure what the difference
    hibernate:
      ddl-auto: update
    #this will show you what the query that fired
    show-sql: true

jwt:
  secret: S/YcQy8pQ+z2Wb/g5q3kP/0n4x8fD9d0j5t1u2v3w4y5z6a7b8c=
  expiration: 86400000 # 86400000 ms = 24 hours